export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const ERROR_HANDLER = 'ERROR_HANDLER';

export const UPDATE_PAGES = 'UPDATE_PAGES';
export const FEED_START = 'FEED_START';
export const FEED_SUCCESS = 'FEED_SUCCESS';
export const FEED_FAIL = 'FEED_FAIL';

export const LIST_START = 'LIST_START';
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const LIST_FAIL = 'LIST_FAIL';

export const LISTS_START = 'LISTS_START';
export const LISTS_SUCCESS = 'LISTS_SUCCESS';
export const LISTS_FAIL = 'LISTS_FAIL';

export const EDIT_LIST_START = 'EDIT_LIST_START';
export const EDIT_LIST_LOAD_START = 'EDIT_LIST_LOAD_START';
export const EDIT_LIST_SUCCESS = 'EDIT_LIST_SUCCESS';
export const EDIT_LIST_FAIL = 'EDIT_LIST_FAIL';

export const RESOURCE_START = 'RESOURCE_START';
export const RESOURCE_SUCCESS = 'RESOURCE_SUCCESS';
export const RESOURCE_FAIL = 'RESOURCE_FAIL';
